services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    init: true

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eproject
    volumes:
      - mongodb_data:/data/db
    init: true

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - product
      - order
    environment:
      - JWT_SECRET=mysecretkey
    restart: on-failure:3
    init: true

  auth:
    build: ./auth
    container_name: auth-service
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_AUTH_URI=mongodb://mongodb:27017/auth_service
      - JWT_SECRET=mysecretkey
    restart: on-failure:3
    init: true

  order:
    build: ./order
    container_name: order-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - MONGODB_ORDER_URI=mongodb://mongodb:27017/order_service
      - JWT_SECRET=mysecretkey
    restart: on-failure:5
    init: true
    command: sh -c "sleep 25 && npm start"

  product:
    build: ./product
    container_name: product-service
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - MONGODB_PRODUCT_URI=mongodb://mongodb:27017/product_service
      - JWT_SECRET=mysecretkey
    restart: on-failure:5
    init: true
    command: sh -c "sleep 25 && npm start"

volumes:
  mongodb_data:
  rabbitmq_data:
